set_location_assignment PIN_Y2  -to CLOCK_50
set_location_assignment PIN_G6  -to PS2_KBCLK
set_location_assignment PIN_H5  -to PS2_KBDAT
set_location_assignment PIN_M23 -to RESET_N
set_location_assignment PIN_L5  -to LCD_ON
set_location_assignment PIN_L4  -to LCD_EN
set_location_assignment PIN_M2  -to LCD_RS
set_location_assignment PIN_M1  -to LCD_RW
set_location_assignment PIN_L3  -to "LCD_DATA[0]"
set_location_assignment PIN_L1  -to "LCD_DATA[1]"
set_location_assignment PIN_L2  -to "LCD_DATA[2]"
set_location_assignment PIN_K7  -to "LCD_DATA[3]"
set_location_assignment PIN_K1  -to "LCD_DATA[4]"
set_location_assignment PIN_K2  -to "LCD_DATA[5]"
set_location_assignment PIN_M3  -to "LCD_DATA[6]"
set_location_assignment PIN_M5  -to "LCD_DATA[7]"